FROM node:18-alpine AS base
WORKDIR /app

COPY package*.json ./

FROM base AS build
ENV NODE_ENV=production
RUN npm install --only=production
COPY . .

RUN npm run build

FROM node:18-alpine AS production
WORKDIR /app

COPY --from=build /app/dist /app/dist
COPY --from=build /app/node_modules /app/node_modules
COPY package*.json ./

CMD ["npm", "run", "start:prod"]

EXPOSE 3000