FROM node:18-alpine3.17 as build

ARG VITE_API_BASE_URL
ARG VITE_GOOGLE_OAUTH_CLIENT_ID
ARG VITE_LLM_API_KEY

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_GOOGLE_OAUTH_CLIENT_ID=$VITE_GOOGLE_OAUTH_CLIENT_ID
ENV VITE_LLM_API_KEY=$VITE_LLM_API_KEY

WORKDIR /app
COPY . /app

RUN npm install
RUN npm run build

FROM ubuntu
RUN apt-get update
RUN apt-get install nginx -y
COPY --from=build /app/dist /var/www/html/
EXPOSE 80
CMD ["nginx","-g","daemon off;"]