name: Frontend deploy

on:
  push:
    branches:
      - docker-deploy

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and test
        run: |
          docker build -t karl . -f Dockerfile.prod

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: . 
          file: Dockerfile.prod 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/karl:${{ github.sha }}

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE }}
          script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/karl:${{ github.sha }}
              docker stop karl-container
              docker rm karl-container 
              docker run -d -p 80:5173 --name karl-container \
                -e VITE_API_BASE_URL="${{ secrets.VITE_API_BASE_URL }}" \
                -e VITE_GOOGLE_OAUTH_CLIENT_ID="${{ secrets.VITE_GOOGLE_OAUTH_CLIENT_ID }}" \
                -e VITE_LLM_API_KEY="${{ secrets.VITE_LLM_API_KEY }}" \
                ${{ secrets.DOCKER_USERNAME }}/karl:${{ github.sha }}